### ISSUE TITLE
New dictionary addition request

### ISSUE THREAD

**Issue by n-manas** [MarvNC/yomichan-dictionaries#16]
Hello,

I did not know how to contact you so excuse me for creating an issue.

I just wanted to let you know that I have created this dictionary from the Corpus of Everyday Japanese Conversation recently released by the National Institute for Japanese Language and Linguistics:
https://github.com/n-manas/Corpus-of-Everyday-Japanese-Conversation---Yomichan-Frequency-Dictionary

Since it might be useful to other learners and your repository is quite referenced, I thought it would be a good idea to let you know so you can add it to the list if you want :)

Have a nice day!

**Comment by MarvNC** [comment]
Hey, just wanted to let you know I'll be linking to my [temporary branch](https://github.com/MarvNC/Corpus-of-Everyday-Japanese-Conversation---Yomichan-Frequency-Dictionary/tree/add-download-table) so that the downloads are more easily accessible. Could you consider looking at the PR I submitted on your repository? I'll link to your original repository when it's done.

**Comment by MarvNC** [comment]
closed, [replaced](https://github.com/forsakeninfinity/CEJC_yomichan_freq_dict)
